# Generated by Django 3.0.3 on 2022-07-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210311_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ig_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tw_link',
        ),
    ]
