# Generated by Django 3.0.3 on 2022-07-06 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('ig_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter Link')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='bgimage/', verbose_name='Backgroung Image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/', verbose_name='Icon Image')),
                ('profession', models.CharField(blank=True, max_length=20, null=True, verbose_name='Profession')),
                ('introduction', models.TextField(blank=True, max_length=500, null=True, verbose_name='Introduction')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
