# Generated by Django 3.0.3 on 2022-09-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content passage')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='thumbnail')),
                ('tag', models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('INSTALLATION', 'INSTALLATION'), ('SERVICES', 'SERVICES'), ('CRAFT', 'CRAFT')], max_length=30, verbose_name='article tag')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post User')),
            ],
        ),
    ]
