# Generated by Django 3.0.3 on 2023-05-09 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20230427_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='Post User'),
        ),
    ]
