# Generated by Django 3.0.3 on 2023-06-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20230616_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Article'},
        ),
    ]
