# Generated by Django 3.0.3 on 2023-06-27 03:28

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_comment_likeforarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
