# Generated by Django 3.0.3 on 2023-07-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20230627_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
