# Generated by Django 3.0.3 on 2023-07-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_subcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcomment',
            options={'ordering': ['created_at']},
        ),
    ]
