# Generated by Django 3.0.3 on 2023-07-26 08:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20230722_1709'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
