# Generated by Django 3.0.3 on 2023-07-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20230726_1709'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
    ]
